export const GET_ALL_MECHANIC_REQUEST = "GET_ALL_MECHANIC_REQUEST";
export const GET_ALL_MECHANIC_SUCCESS = "GET_ALL_MECHANIC_SUCCESS";
export const GET_ALL_MECHANIC_FAIL = "GET_ALL_MECHANIC_FAIL";


export const REGISTER_WORKER_REQUEST = "REGISTER_WORKER_REQUEST";
export const REGISTER_WORKER_SUCCESS = "REGISTER_WORKER_SUCCESS";
export const REGISTER_WORKER_FAIL = "REGISTER_WORKER_FAIL";

export const WORKER_LOGIN_REQUEST = "WORKER_LOGIN_REQUEST";
export const WORKER_LOGIN_SUCCESS = "WORKER_LOGIN_SUCCESS";
export const WORKER_LOGIN_FAIL = "WORKER_LOGIN_FAIL";


