export const GET_ALL_MECHANIC_REQUEST = "GET_ALL_MECHANIC_REQUEST";
export const GET_ALL_MECHANIC_SUCCESS = "GET_ALL_MECHANIC_SUCCESS";
export const GET_ALL_MECHANIC_FAIL = "GET_ALL_MECHANIC_FAIL";


export const REGISTER_WORKER_REQUEST = "REGISTER_WORKER_REQUEST";
export const REGISTER_WORKER_SUCCESS = "REGISTER_WORKER_SUCCESS";
export const REGISTER_WORKER_FAIL = "REGISTER_WORKER_FAIL";

export const WORKER_LOGIN_REQUEST = "WORKER_LOGIN_REQUEST";
export const WORKER_LOGIN_SUCCESS = "WORKER_LOGIN_SUCCESS";
export const WORKER_LOGIN_FAIL = "WORKER_LOGIN_FAIL";


export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SERVICE_REQUEST = "SERVICE_REQUEST";
export const SERVICE_SUCCESS = "SERVICE_SUCCESS";
export const SERVICE_FAIL = "SERVICE_FAIL";

export const GET_USER_ORDERS_REQUEST = "GET_USER_ORDERS_REQUEST";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FAIL = "GET_USER_ORDERS_FAIL";

export const GET_WORKER_ORDERS_REQUEST = "GET_WORKER_ORDERS_REQUEST";
export const GET_WORKER_ORDERS_SUCCESS = "GET_WORKER_ORDERS_SUCCESS";
export const GET_WORKER_ORDERS_FAIL = "GET_WORKER_ORDERS_FAIL";


export const CLEAR_ORDER_SUCCESS = "CLEAR_ORDER_SUCCESS";
export const CLEAR_ORDER_FAIL = "CLEAR_ORDER_FAIL";

